;; -*- mode: eask; lexical-binding: t -*-

(package "project-to-org"
         "0.1.0"
         "Sync GitHub Projects to Org-mode")

(website-url "https://github.com/ewilderj/project-to-org")
(keywords "tools" "org" "github")

(package-file "project-to-org.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")

(development
 (depends-on "buttercup"))
